name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Install discord.js
      run: npm install discord.js
    - name: Install nodemon
      run: npm install nodemon
    -name: Install dotenv
      run: npm install dotenv
